
#
# This LookML file was generated by AtScale on 2024-09-07T14:32:40.030814511Z
#
# AtScale version: C2024.8.0
# Catalog: gbq_costs_main

connection: "atscale_mm"
label: "gbq_costs_main"


include: "/views/gbq__costs__main/gbq_costs.view.lkml"


explore: gbq_costs {
  label: "gbq costs"
}

