
#
# This LookML file was generated by AtScale on 2024-08-13T13:20:40.591840087Z
#
# AtScale version: C2024.1.0
# Catalog: Sales Insights - gbq_main

connection: "atscale_mm_container"
label: "Sales Insights - gbq_main"


include: "/views/Sales_Insights_-_gbq__main/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

