
#
# This LookML file was generated by AtScale on 2024-08-30T08:41:57.260407924Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - Snowflake_main

connection: "atscale_mm_container"
label: "Sales Insights - Snowflake_main"


include: "/views/Sales_Insights_-_Snowflake__main/Internet_Sales.view.lkml"

include: "/views/Sales_Insights_-_Snowflake__main/Demo.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

explore: Demo {
  label: "Demo"
}

