
#
# This LookML file was generated by AtScale on 2024-09-23T09:59:28.633734795Z
#
# AtScale version: C2024.8.1
# Catalog: Sales Insights - Snowflake_main

connection: "atscale_mm"
label: "Sales Insights - Snowflake_main"


include: "/views/Sales_Insights_-_Snowflake__main/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

