
#
# This LookML file was generated by AtScale on 2024-09-23T11:32:15.055389761Z
#
# AtScale version: C2024.8.1
# Catalog: Sales Insights - Snowflake_demo

connection: "atscale_mm"
label: "Sales Insights - Snowflake_demo"


include: "/views/Sales_Insights_-_Snowflake__demo/Internet_Sales.view.lkml"

include: "/views/Sales_Insights_-_Snowflake__demo/Demo.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

explore: Demo {
  label: "Demo"
}

