
#
# This LookML file was generated by AtScale on 2024-09-18T13:28:26.350802380Z
#
# AtScale version: C2024.8.1
# Catalog: Sales Insights - gbq_main

connection: "atscale_mm"
label: "Sales Insights - gbq_main"


include: "/views/Sales_Insights_-_gbq__main/Internet_Sales.view.lkml"

include: "/views/Sales_Insights_-_gbq__main/Demo.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

explore: Demo {
  label: "Demo"
}

