
#
# This LookML file was generated by AtScale on 2024-08-30T11:23:37.506467137Z
#
# AtScale version: C2024.8.0
# Catalog: veolia_main

connection: "atscale_mm_container"
label: "veolia_main"


include: "/views/veolia__main/Veolia_Italy.view.lkml"


explore: Veolia_Italy {
  label: "Veolia Italy"
}

